#!/bin/sh

subst='$Format:%d$'

# Determine the version string to build into a binary.
# When building in the git repository, we can use the output 
# of "git describe" which gives an unequivocal answer.
#
# Failing that, we use variable above 
# which has a set of references substituted into it by git.
# If we can find one which matches $v[0-9].* then we assume it's
# a version-number tag, else we just use the whole string.
# If there is more than one v[0-9].* tag, sort them and use the
# first. This favours, eg v2.63 over 2.63rc6.

if which git >/dev/null 2>&1 && [ -d .git ]; then
     git describe
elif echo $subst | grep '\$Format:%d\$' >/dev/null 2>&1; then
# unsubstituted file, but no git available.
    echo UNKNOWN
else
     vers=`echo $subst | sed 's/[(), ]/,/ g' | tr ',' '\n' | grep $v[0-9]`

     if [ $? -eq 0 ]; then
         echo "${vers}" | sort | head -n 1 | sed 's/^v//'
     else
         echo $subst
     fi
fi

exit 0

